# Welcome to Jekyll!

# Website settings
title: "Vladyslav Shkola personal blog"
description: "Vladyslav Shkola personal blog. Github pages"
keywords: "Vladyslav,Shkola,blog,vshkola,github,gh-pages"
baseurl: "/"
url: "vshkola.github.com"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# author
author:
  first_name: 'Vladyslav'
  last_name: 'Shkola'
  email: 'vladyslav.shkola@gmail.com'
  github_username: 'vshkola'
  head_img: 'static/img/landing/vlad.jpg'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
project:
  saplatform:
    name: 'Machine Learning by Andrew Ng'
    url: '/MachineLearningCoursera/'
    img: 'static/img/landing/ML_course.png'
  jalpc:
    name: 'Titanic - Kaggle challenge'
    url: '/titanickagglechallenge'
    img: 'statis/img/landing/kaggle.png'
# blog index
index:
  home: 'Home'
  links: 'Links'

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
