# Welcome to Jekyll!

# Website settings
title: "Vladyslav Shkola personal blog"
description: "Vladyslav Shkola personal blog. Github pages"
keywords: "Vladyslav,Shkola,blog,vshkola,github,gh-pages"
baseurl: "/"
url: "vshkola.github.com"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# author
author:
  first_name: 'Vladyslav'
  last_name: 'Shkola'
  email: 'vladyslav.shkola@gmail.com'
  github_username: 'vshkola'
  head_img: 'static/img/landing/vlad.jpg'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
project:
  saplatform:
    name: 'Machine Learning by Andrew Ng'
    url: '/MachineLearningCoursera/'
    img: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera.s3.amazonaws.com/topics/ml/large-icon.png'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
